USE QLDatMon
ALTER TABLE dbo.DONHANG
ALTER COLUMN CMND CHAR(8) NULL;

ALTER TABLE dbo.CHINHANHCH
ALTER COLUMN THOIGIANMOCUA TIME

ALTER TABLE dbo.CHINHANHCH
ALTER COLUMN THOIGIANDONGCUA TIME

SELECT*FROM dbo.CHINHANHCH

SELECT*
FROM dbo.TAIKHOANNH

SELECT*FROM dbo.DONHANG dh JOIN dbo.CHITIETDONHANG ct ON ct.MADON = dh.MADON

DELETE dbo.CHITIETDONHANG WHERE MADON = 'DH000002'
DELETE dbo.DONHANG WHERE MADON = 'DH000002'

SELECT*FROM dbo.MONAN

INSERT DonHang(MADON, MADT, DIACHICH, MAKH) VALUES ('DH000001', 'DT000001', N'Lê Lai', 'KH000001')

SELECT*FROM dbo.DONHANG dh JOIN dbo.CHITIETDONHANG ct ON ct.MADON = dh.MADON

SET NOCOUNT ON

DELETE dbo.CHITIETDONHANG WHERE MADON IN (SELECT MADON FROM dbo.DONHANG WHERE MAKH = 'KH000001')
DELETE dbo.DONHANG WHERE MAKH = 'KH000001'

SELECT*
FROM dbo.CHITIETDONHANG

INSERT DonHang(MADON, MADT, DIACHICH, MAKH) VALUES('DH000001', 'DT000001', N'Lê Lai', 'KH000001')

SELECT*
FROM dbo.DONHANG

DELETE dbo.MONAN WHERE MADT = 'DT000001'